--- 
- hosts: dcos-cluster,dcos-bootstrap
  become: yes
  roles:
    - ansible-dcos-common
  tags:
    - common
    - ansible-dcos-common

- hosts: dcos-bootstrap
  roles:
    - ansible-dcos-bootstrap-node
  tags:
    - bootstrap
    - ansible-dcos-bootstrap-node

- hosts: mesos-master
  become: yes
  roles:
    - ansible-dcos-bootstrap-master
  tags:
    - bootstrap
    - ansible-dcos-bootstrap-master

- hosts: mesos-agent
  become: yes
  roles:
    - bootstrap-mesos-agent
  tags:
    - bootstrap
    - bootstrap-mesos-agent